FROM esp_base:ghrVersion
RUN set -ex && \
    /usr/bin/pip3 install astroid==2.11.5 \
                          coverage==6.3.2 \
                          isort==5.10.1 \
                          pycodestyle==2.8.0 \
                          pylint==2.13.8 \
                          pytest==7.1.2 \
                          pytest-cov==3.0.0 && \
   mkdir -p /proj/data/ldtk && \
   rm -rf ${HOME}/.cache
