FROM esp_base:ghrVersion
RUN set -ex && \
    /usr/bin/pip3 install astroid==1.5.3 \
                          coverage==4.4.1 \
                          pycodestyle==2.4.0 \
                          pylint==1.7.2 \
                          pytest==3.1.3 \
                          pytest-cov==2.5.1 && \
   mkdir -p /proj/data/ldtk && \
   rm -rf ${HOME}/.cache
