FROM esp_base:ghrVersion
ENV DAWGIE_AE_BASE_PATH /proj/src/ae/excalibur
ENV DAWGIE_AE_BASE_PACKAGE excalibur
ENV DAWGIE_DB_HOST mentor.jpl.nasa.gov
ENV DAWGIE_DB_IMPL post
ENV DAWGIE_DB_NAME ops
ENV DAWGIE_DB_PATH sdpuser:h8pwds!
ENV DAWGIE_DB_PORT 5263
ENV DAWGIE_DOCKERIZED_GIT_REVISION irrelevant
ENV GNUPGHOME /proj/gnupg
ENV HOME /proj/src
ENV PYTHONPATH /proj/src/ae
ENTRYPOINT ["python3", "-m"]
