services:
  base:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.base
    image: esp/base:${ESP_VERSION}
  pipeline:
    build:
      args:
        BASE_VER: ${ESP_VERSION}
      context: ..
      dockerfile: .docker/Dockerfile.server
    container_name: pipeline-${EXCALIBUR_USER}
    depends_on:
      - base
    environment:
      - DAWGIE_AE_BASE_PACKAGE=${DAWGIE_AE_BASE_PACKAGE}
      - DAWGIE_AE_BASE_PATH=${DAWGIE_AE_BASE_PATH}
      - DAWGIE_DB_HOST=${DAWGIE_DB_HOST}
      - DAWGIE_DB_IMPL=${DAWGIE_DB_IMPL}
      - DAWGIE_DB_NAME=${DAWGIE_DB_NAME}
      - DAWGIE_DB_PATH=${DAWGIE_DB_PATH}
      - DAWGIE_FE_PATH=${DAWGIE_FE_PATH}
      - DAWGIE_LISTENER_BACKLOG=${DAWGIE_LISTENER_BACKLOG}
      - DAWGIE_LOG_BACKUP=${DAWGIE_LOG_BACKUP}
      - DAWGIE_SSL_PEM_FILE=${DAWGIE_SSL_PEM_FILE}
      - DAWGIE_SSL_PEM_MYNAME=${DAWGIE_SSL_PEM_MYNAME}
      - DAWGIE_SSL_PEM_MYSELF=${DAWGIE_SSL_PEM_MYSELF}
      - EXCALIBUR_LEVER_AND_KNOB_SETTINGS=${EXCALIBUR_LEVER_AND_KNOB_SETTINGS}
      - EXCALIBUR_LOG_LEVEL=${EXCALIBUR_LOG_LEVEL}
      - EXCALIBUR_USER=${EXCALIBUR_USER}
      - USERNAME=${USERNAME}
    image: esp/server:${ESP_VERSION}
    ports:
      - "${DAWGIE_FE_PORT:-9990}-${DAWGIE_SFE_PORT:-9995}:9090-9095"
    user: "${EXCALIBUR_UID}:${EXCALIBUR_GID}"
    volumes:
      - ${EXCALIBUR_CERTS}:/proj/data/certs:ro
      - ${EXCALIBUR_DATA_PATH}:/proj/data
      - ${EXCALIBUR_DB_PATH}:/proj/data/db
      - ${EXCALIBUR_DATA_PATH}/logs:/proj/logs
      - ${EXCALIBUR_SOURCE_PATH}:/proj/src/ae
      - /etc/ssl:/etc/ssl:ro
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
      - /usr/share/ca-certificates:/usr/share/ca-certificates:ro

  tools:
    build:
      args:
        BASE_VER: ${ESP_VERSION}
      context: ..
      dockerfile: .docker/Dockerfile.tools
    depends_on:
      - base
    environment:
      - EXCALIBUR_USER=${EXCALIBUR_USER}
      - USERNAME=${USERNAME}
    image: esp/tools:${ESP_VERSION}
    user: "${EXCALIBUR_UID}:${EXCALIBUR_GID}"
    volumes:
      - ${EXCALIBUR_DATA_PATH}:/proj/data

  workers:
    build:
      args:
        BASE_VER: ${ESP_VERSION}
      context: ..
      dockerfile: .docker/Dockerfile.worker
    depends_on:
      - base
    deploy:
      mode: replicated
      replicas: ${EXCALIBUR_REPLICAS}
      restart_policy:
        condition: any
        delay: 3s
    environment:
      - DAWGIE_SSL_PEM_FILE=${DAWGIE_SSL_PEM_FILE}
      - DAWGIE_SSL_PEM_MYNAME=${DAWGIE_SSL_PEM_MYNAME}
      - DAWGIE_SSL_PEM_MYSELF=${DAWGIE_SSL_PEM_MYSELF}
      - EXCALIBUR_USER=${EXCALIBUR_USER}
      - USERNAME=${USERNAME}
    image: esp/worker:latest
    init: true
    user: "${EXCALIBUR_UID}:${EXCALIBUR_GID}"
    volumes:
      - ${EXCALIBUR_CERTS}:/proj/data/certs:ro
      - ${EXCALIBUR_DATA_PATH}:/proj/data
      - /etc/ssl:/etc/ssl:ro
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
      - /usr/share/ca-certificates:/usr/share/ca-certificates:ro
    
