ARG BASE_VER
FROM esp/base:$BASE_VER
ENV HOME=/proj/src
ENV PYTHONPATH=/proj/src/ae
ENTRYPOINT ["python", "-m", "dawgie.pl", "--context=excalibur.context"],

# for ops
#    "--context-db-impl=post", \
#            "--context-db-name=ops", \
#            "--context-db-port=5263", \
#            "--context-log-backup=10000"]
